In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/exo-data/testing.npy
/kaggle/input/exo-data/error_bars.npy
/kaggle/input/exo-data/training.npy
/kaggle/input/exo-data/wavelength.npy
/kaggle/input/exo-data/WASP12b.npy

In [2]:
!pip install pycaret

Collecting pycaret
  Downloading pycaret-3.0.0-py3-none-any.whl (481 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 481.8/481.8 kB 9.4 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: wurlitzer in /opt/conda/lib/python3.7/site-packages (from pycaret) (3.0.3)
Requirement already satisfied: numba>=0.55.0 in /opt/conda/lib/python3.7/site-packages (from pycaret) (0.56.4)
Requirement already satisfied: scikit-plot>=0.3.7 in /opt/conda/lib/python3.7/site-packages (from pycaret) (0.3.7)
Requirement already satisfied: lightgbm>=3.0.0 in /opt/conda/lib/python3.7/site-packages (from pycaret) (3.3.2)
Requirement already satisfied: plotly>=5.0.0 in /opt/conda/lib/python3.7/site-packages (from pycaret) (5.13.0)
Collecting pyod>=1.0.8
  Downloading pyod-1.0.9.tar.gz (149 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.0/150.0 kB 12.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: nbformat>=4.2.0 in /opt/conda/lib/python3.7/site-packages (from pycaret) (5.7.3)
Collecting plotly-resampler>=0.8.3.1
  Downloading plotly_resampler-0.8.3.2.tar.gz (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.4/46.4 kB 4.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: tqdm>=4.62.0 in /opt/conda/lib/python3.7/site-packages (from pycaret) (4.64.1)
Requirement already satisfied: joblib>=1.2.0 in /opt/conda/lib/python3.7/site-packages (from pycaret) (1.2.0)
Requirement already satisfied: pandas<1.6.0,>=1.3.0 in /opt/conda/lib/python3.7/site-packages (from pycaret) (1.3.5)
Requirement already satisfied: scipy<2.0.0 in /opt/conda/lib/python3.7/site-packages (from pycaret) (1.7.3)
Requirement already satisfied: xxhash in /opt/conda/lib/python3.7/site-packages (from pycaret) (3.2.0)
Requirement already satisfied: cloudpickle in /opt/conda/lib/python3.7/site-packages (from pycaret) (2.2.1)
Requirement already satisfied: matplotlib>=3.3.0 in /opt/conda/lib/python3.7/site-packages (from pycaret) (3.5.3)
Requirement already satisfied: jinja2>=1.2 in /opt/conda/lib/python3.7/site-packages (from pycaret) (3.1.2)
Requirement already satisfied: yellowbrick>=1.4 in /opt/conda/lib/python3.7/site-packages (from pycaret) (1.5)
Requirement already satisfied: requests>=2.27.1 in /opt/conda/lib/python3.7/site-packages (from pycaret) (2.28.2)
Requirement already satisfied: deprecation>=2.1.0 in /opt/conda/lib/python3.7/site-packages (from pycaret) (2.1.0)
Requirement already satisfied: imbalanced-learn>=0.8.1 in /opt/conda/lib/python3.7/site-packages (from pycaret) (0.10.1)
Requirement already satisfied: ipywidgets>=7.6.5 in /opt/conda/lib/python3.7/site-packages (from pycaret) (7.7.1)
Requirement already satisfied: psutil>=5.9.0 in /opt/conda/lib/python3.7/site-packages (from pycaret) (5.9.3)
Requirement already satisfied: markupsafe>=2.0.1 in /opt/conda/lib/python3.7/site-packages (from pycaret) (2.1.1)
Collecting importlib-metadata>=4.12.0
  Using cached importlib_metadata-6.4.1-py3-none-any.whl (22 kB)
Collecting tbats>=1.1.0
  Downloading tbats-1.1.2-py3-none-any.whl (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.8/43.8 kB 4.0 MB/s eta 0:00:00
Collecting pickle5
  Downloading pickle5-0.0.12-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (256 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 256.4/256.4 kB 20.8 MB/s eta 0:00:00
Requirement already satisfied: category-encoders>=2.4.0 in /opt/conda/lib/python3.7/site-packages (from pycaret) (2.6.0)
Requirement already satisfied: ipython>=5.5.0 in /opt/conda/lib/python3.7/site-packages (from pycaret) (7.34.0)
Collecting kaleido>=0.2.1
  Downloading kaleido-0.2.1-py2.py3-none-manylinux1_x86_64.whl (79.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.9/79.9 MB 13.1 MB/s eta 0:00:0000:0100:01
Collecting schemdraw>=0.14
  Downloading schemdraw-0.15-py3-none-any.whl (106 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.8/106.8 kB 8.5 MB/s eta 0:00:00
Requirement already satisfied: numpy<1.25,>=1.21 in /opt/conda/lib/python3.7/site-packages (from pycaret) (1.21.6)
Requirement already satisfied: statsmodels>=0.12.1 in /opt/conda/lib/python3.7/site-packages (from pycaret) (0.13.5)
Collecting pmdarima!=1.8.1,<3.0.0,>=1.8.0
  Downloading pmdarima-2.0.3-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 59.1 MB/s eta 0:00:00
Collecting sktime>=0.16.1
  Downloading sktime-0.17.1-py3-none-any.whl (16.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.1/16.1 MB 60.5 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: scikit-learn>=1.0 in /opt/conda/lib/python3.7/site-packages (from pycaret) (1.0.2)
Requirement already satisfied: patsy>=0.5.1 in /opt/conda/lib/python3.7/site-packages (from category-encoders>=2.4.0->pycaret) (0.5.3)
Requirement already satisfied: packaging in /opt/conda/lib/python3.7/site-packages (from deprecation>=2.1.0->pycaret) (23.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/conda/lib/python3.7/site-packages (from imbalanced-learn>=0.8.1->pycaret) (3.1.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /opt/conda/lib/python3.7/site-packages (from importlib-metadata>=4.12.0->pycaret) (4.4.0)
Requirement already satisfied: zipp>=0.5 in /opt/conda/lib/python3.7/site-packages (from importlib-metadata>=4.12.0->pycaret) (3.11.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /opt/conda/lib/python3.7/site-packages (from ipython>=5.5.0->pycaret) (3.0.36)
Requirement already satisfied: setuptools>=18.5 in /opt/conda/lib/python3.7/site-packages (from ipython>=5.5.0->pycaret) (59.8.0)
Requirement already satisfied: matplotlib-inline in /opt/conda/lib/python3.7/site-packages (from ipython>=5.5.0->pycaret) (0.1.6)
Requirement already satisfied: decorator in /opt/conda/lib/python3.7/site-packages (from ipython>=5.5.0->pycaret) (5.1.1)
Requirement already satisfied: pexpect>4.3 in /opt/conda/lib/python3.7/site-packages (from ipython>=5.5.0->pycaret) (4.8.0)
Requirement already satisfied: jedi>=0.16 in /opt/conda/lib/python3.7/site-packages (from ipython>=5.5.0->pycaret) (0.18.2)
Requirement already satisfied: backcall in /opt/conda/lib/python3.7/site-packages (from ipython>=5.5.0->pycaret) (0.2.0)
Requirement already satisfied: pygments in /opt/conda/lib/python3.7/site-packages (from ipython>=5.5.0->pycaret) (2.14.0)
Requirement already satisfied: pickleshare in /opt/conda/lib/python3.7/site-packages (from ipython>=5.5.0->pycaret) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /opt/conda/lib/python3.7/site-packages (from ipython>=5.5.0->pycaret) (5.8.1)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /opt/conda/lib/python3.7/site-packages (from ipywidgets>=7.6.5->pycaret) (3.6.4)
Requirement already satisfied: ipykernel>=4.5.1 in /opt/conda/lib/python3.7/site-packages (from ipywidgets>=7.6.5->pycaret) (6.16.2)
Requirement already satisfied: ipython-genutils~=0.2.0 in /opt/conda/lib/python3.7/site-packages (from ipywidgets>=7.6.5->pycaret) (0.2.0)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /opt/conda/lib/python3.7/site-packages (from ipywidgets>=7.6.5->pycaret) (3.0.5)
Requirement already satisfied: wheel in /opt/conda/lib/python3.7/site-packages (from lightgbm>=3.0.0->pycaret) (0.38.4)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.7/site-packages (from matplotlib>=3.3.0->pycaret) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/conda/lib/python3.7/site-packages (from matplotlib>=3.3.0->pycaret) (1.4.4)
Requirement already satisfied: pyparsing>=2.2.1 in /opt/conda/lib/python3.7/site-packages (from matplotlib>=3.3.0->pycaret) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.7/site-packages (from matplotlib>=3.3.0->pycaret) (2.8.2)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.7/site-packages (from matplotlib>=3.3.0->pycaret) (4.38.0)
Requirement already satisfied: pillow>=6.2.0 in /opt/conda/lib/python3.7/site-packages (from matplotlib>=3.3.0->pycaret) (9.4.0)
Requirement already satisfied: jsonschema>=2.6 in /opt/conda/lib/python3.7/site-packages (from nbformat>=4.2.0->pycaret) (4.17.3)
Requirement already satisfied: fastjsonschema in /opt/conda/lib/python3.7/site-packages (from nbformat>=4.2.0->pycaret) (2.16.2)
Requirement already satisfied: jupyter-core in /opt/conda/lib/python3.7/site-packages (from nbformat>=4.2.0->pycaret) (4.12.0)
Requirement already satisfied: llvmlite<0.40,>=0.39.0dev0 in /opt/conda/lib/python3.7/site-packages (from numba>=0.55.0->pycaret) (0.39.1)
Requirement already satisfied: pytz>=2017.3 in /opt/conda/lib/python3.7/site-packages (from pandas<1.6.0,>=1.3.0->pycaret) (2022.7.1)
Requirement already satisfied: tenacity>=6.2.0 in /opt/conda/lib/python3.7/site-packages (from plotly>=5.0.0->pycaret) (8.1.0)
Requirement already satisfied: orjson<4.0.0,>=3.8.0 in /opt/conda/lib/python3.7/site-packages (from plotly-resampler>=0.8.3.1->pycaret) (3.8.5)
Collecting jupyter-dash>=0.4.2
  Downloading jupyter_dash-0.4.2-py3-none-any.whl (23 kB)
Collecting trace-updater>=0.0.8
  Downloading trace_updater-0.0.9.1-py3-none-any.whl (185 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 185.2/185.2 kB 16.5 MB/s eta 0:00:00
Collecting dash<3.0.0,>=2.2.0
  Downloading dash-2.9.3-py3-none-any.whl (10.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 75.9 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: Cython!=0.29.18,!=0.29.31,>=0.29 in /opt/conda/lib/python3.7/site-packages (from pmdarima!=1.8.1,<3.0.0,>=1.8.0->pycaret) (0.29.34)
Requirement already satisfied: urllib3 in /opt/conda/lib/python3.7/site-packages (from pmdarima!=1.8.1,<3.0.0,>=1.8.0->pycaret) (1.26.14)
Requirement already satisfied: six in /opt/conda/lib/python3.7/site-packages (from pyod>=1.0.8->pycaret) (1.16.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.7/site-packages (from requests>=2.27.1->pycaret) (3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.7/site-packages (from requests>=2.27.1->pycaret) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.7/site-packages (from requests>=2.27.1->pycaret) (2022.12.7)
Collecting deprecated>=1.2.13
  Downloading Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
Requirement already satisfied: Flask>=1.0.4 in /opt/conda/lib/python3.7/site-packages (from dash<3.0.0,>=2.2.0->plotly-resampler>=0.8.3.1->pycaret) (2.2.3)
Collecting dash-table==5.0.0
  Downloading dash_table-5.0.0-py3-none-any.whl (3.9 kB)
Collecting dash-html-components==2.0.0
  Downloading dash_html_components-2.0.0-py3-none-any.whl (4.1 kB)
Collecting dash-core-components==2.0.0
  Downloading dash_core_components-2.0.0-py3-none-any.whl (3.8 kB)
Requirement already satisfied: wrapt<2,>=1.10 in /opt/conda/lib/python3.7/site-packages (from deprecated>=1.2.13->sktime>=0.16.1->pycaret) (1.14.1)
Requirement already satisfied: pyzmq>=17 in /opt/conda/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (25.0.0)
Requirement already satisfied: jupyter-client>=6.1.12 in /opt/conda/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (7.4.9)
Requirement already satisfied: nest-asyncio in /opt/conda/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (1.5.6)
Requirement already satisfied: debugpy>=1.0 in /opt/conda/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (1.6.6)
Requirement already satisfied: tornado>=6.1 in /opt/conda/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (6.2)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /opt/conda/lib/python3.7/site-packages (from jedi>=0.16->ipython>=5.5.0->pycaret) (0.8.3)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /opt/conda/lib/python3.7/site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (0.19.3)
Requirement already satisfied: importlib-resources>=1.4.0 in /opt/conda/lib/python3.7/site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (5.10.2)
Requirement already satisfied: pkgutil-resolve-name>=1.3.10 in /opt/conda/lib/python3.7/site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (1.3.10)
Requirement already satisfied: attrs>=17.4.0 in /opt/conda/lib/python3.7/site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (22.2.0)
Collecting ansi2html
  Downloading ansi2html-1.8.0-py3-none-any.whl (16 kB)
Requirement already satisfied: retrying in /opt/conda/lib/python3.7/site-packages (from jupyter-dash>=0.4.2->plotly-resampler>=0.8.3.1->pycaret) (1.3.4)
Requirement already satisfied: ptyprocess>=0.5 in /opt/conda/lib/python3.7/site-packages (from pexpect>4.3->ipython>=5.5.0->pycaret) (0.7.0)
Requirement already satisfied: wcwidth in /opt/conda/lib/python3.7/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.5.0->pycaret) (0.2.6)
Requirement already satisfied: notebook>=4.4.1 in /opt/conda/lib/python3.7/site-packages (from widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (6.5.2)
Requirement already satisfied: itsdangerous>=2.0 in /opt/conda/lib/python3.7/site-packages (from Flask>=1.0.4->dash<3.0.0,>=2.2.0->plotly-resampler>=0.8.3.1->pycaret) (2.1.2)
Requirement already satisfied: Werkzeug>=2.2.2 in /opt/conda/lib/python3.7/site-packages (from Flask>=1.0.4->dash<3.0.0,>=2.2.0->plotly-resampler>=0.8.3.1->pycaret) (2.2.3)
Requirement already satisfied: click>=8.0 in /opt/conda/lib/python3.7/site-packages (from Flask>=1.0.4->dash<3.0.0,>=2.2.0->plotly-resampler>=0.8.3.1->pycaret) (8.1.3)
Requirement already satisfied: entrypoints in /opt/conda/lib/python3.7/site-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (0.4)
Requirement already satisfied: Send2Trash>=1.8.0 in /opt/conda/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (1.8.0)
Requirement already satisfied: terminado>=0.8.3 in /opt/conda/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (0.17.1)
Requirement already satisfied: nbclassic>=0.4.7 in /opt/conda/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (0.4.8)
Requirement already satisfied: prometheus-client in /opt/conda/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (0.15.0)
Requirement already satisfied: argon2-cffi in /opt/conda/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (21.3.0)
Requirement already satisfied: nbconvert>=5 in /opt/conda/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (6.4.5)
Requirement already satisfied: notebook-shim>=0.1.0 in /opt/conda/lib/python3.7/site-packages (from nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (0.2.2)
Requirement already satisfied: jupyter-server>=1.8 in /opt/conda/lib/python3.7/site-packages (from nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (1.23.5)
Requirement already satisfied: defusedxml in /opt/conda/lib/python3.7/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /opt/conda/lib/python3.7/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (0.2.2)
Requirement already satisfied: pandocfilters>=1.4.1 in /opt/conda/lib/python3.7/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (1.5.0)
Requirement already satisfied: mistune<2,>=0.8.1 in /opt/conda/lib/python3.7/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (0.8.4)
Requirement already satisfied: bleach in /opt/conda/lib/python3.7/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (6.0.0)
Requirement already satisfied: beautifulsoup4 in /opt/conda/lib/python3.7/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (4.11.1)
Requirement already satisfied: testpath in /opt/conda/lib/python3.7/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (0.6.0)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in /opt/conda/lib/python3.7/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (0.5.13)
Requirement already satisfied: argon2-cffi-bindings in /opt/conda/lib/python3.7/site-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (21.2.0)
Requirement already satisfied: websocket-client in /opt/conda/lib/python3.7/site-packages (from jupyter-server>=1.8->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (1.4.2)
Requirement already satisfied: anyio<4,>=3.1.0 in /opt/conda/lib/python3.7/site-packages (from jupyter-server>=1.8->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (3.6.2)
Requirement already satisfied: cffi>=1.0.1 in /opt/conda/lib/python3.7/site-packages (from argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (1.15.1)
Requirement already satisfied: soupsieve>1.2 in /opt/conda/lib/python3.7/site-packages (from beautifulsoup4->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (2.3.2.post1)
Requirement already satisfied: webencodings in /opt/conda/lib/python3.7/site-packages (from bleach->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (0.5.1)
Requirement already satisfied: sniffio>=1.1 in /opt/conda/lib/python3.7/site-packages (from anyio<4,>=3.1.0->jupyter-server>=1.8->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (1.3.0)
Requirement already satisfied: pycparser in /opt/conda/lib/python3.7/site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (2.21)
Building wheels for collected packages: plotly-resampler, pyod
  Building wheel for plotly-resampler (pyproject.toml) ... done
  Created wheel for plotly-resampler: filename=plotly_resampler-0.8.3.2-cp37-cp37m-manylinux_2_31_x86_64.whl size=75912 sha256=98b0ab2995f3c60368f743f3ffe2cf36340ce980f182090525249d0ad5a2dabc
  Stored in directory: /root/.cache/pip/wheels/20/76/b6/bd15d35379014d2c71ddfbecc2d1e01713a1ad69a600717f85
  Building wheel for pyod (setup.py) ... done
  Created wheel for pyod: filename=pyod-1.0.9-py3-none-any.whl size=184113 sha256=2a0fa6002bc65fea0dbd5125062af976bb369f9d8ce2374d7528fd0ba86b95ce
  Stored in directory: /root/.cache/pip/wheels/15/7d/6b/997e911ae52e5ddebceb467e96797ce99e9e8bd9d3c5e0727a
Successfully built plotly-resampler pyod
Installing collected packages: trace-updater, kaleido, dash-table, dash-html-components, dash-core-components, schemdraw, pickle5, importlib-metadata, deprecated, ansi2html, sktime, pyod, pmdarima, dash, tbats, jupyter-dash, plotly-resampler, pycaret
  Attempting uninstall: importlib-metadata
    Found existing installation: importlib-metadata 4.11.4
    Uninstalling importlib-metadata-4.11.4:
      Successfully uninstalled importlib-metadata-4.11.4

In [3]:
from pycaret.regression import *
import pandas as pd

In [4]:
data = np.load("/kaggle/input/exo-data/training.npy")
data2 = np.load("/kaggle/input/exo-data/testing.npy")

In [5]:
pred_data = np.load("/kaggle/input/exo-data/WASP12b.npy")
new_data = pd.DataFrame(pred_data)

In [6]:
data1 = data[:,:14]
df1 = pd.DataFrame(data1)
data3 = data2[:,:14]
testdata = pd.DataFrame(data3)

In [7]:
s = setup(data = df1, train_size = 1.0 , test_data = testdata, target='13', session_id = 123, use_gpu=False, 
          normalize = True, normalize_method = 'minmax')

In [8]:
et = create_model('et', fold=5)

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

In [9]:
predictions_et = predict_model(et, data=new_data)
predictions_et

,0,1,2,3,4,5,6,7,8,9,10,11,12,prediction_label
0,1.4441,1.4422,1.4402,1.4428,1.4391,1.4386,1.4365,1.4327,1.4582,1.46,1.453,1.4475,1.4332,1058.562364

In [10]:
rf = create_model('rf', fold=5)

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

In [11]:
predictions_rf = predict_model(rf, data=new_data)
predictions_rf

,0,1,2,3,4,5,6,7,8,9,10,11,12,prediction_label
0,1.4441,1.4422,1.4402,1.4428,1.4391,1.4386,1.4365,1.4327,1.4582,1.46,1.453,1.4475,1.4332,1190.867526

In [12]:
#tuned_et, tuner = tune_model(et, fold=10,return_tuner=True, n_iter = 10 , return_train_score=True)

In [13]:
#tuned_rf, tuner = tune_model(rf, fold=10,return_tuner=True, n_iter = 10 , return_train_score=True)

In [14]:
#save_model(et, 'my_first_et_model')

In [15]:
#save_model(rf, 'my_first_rf_model')

### Water

In [16]:
dataw1 = data[:,:14]
dataw1[:,13:14] = data[:,14:15]

In [17]:
dfw1 = pd.DataFrame(dataw1)
dataw2 = data2[:,:14]
dataw2[:,13:14] = data2[:,14:15]
testdataw = pd.DataFrame(dataw2)

In [18]:
sw = setup(data = dfw1, train_size = 1.0 , test_data = testdataw, target='13', session_id = 123, use_gpu=False, 
          normalize = True, normalize_method = 'minmax')

In [19]:
et = create_model('et', fold=5)

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

In [20]:
predictions_et = predict_model(et, data=new_data)
predictions_et

,0,1,2,3,4,5,6,7,8,9,10,11,12,prediction_label
0,1.4441,1.4422,1.4402,1.4428,1.4391,1.4386,1.4365,1.4327,1.4582,1.46,1.453,1.4475,1.4332,-2.565071

In [21]:
rf = create_model('rf', fold=5)

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

In [22]:
predictions_rf = predict_model(rf, data=new_data)
predictions_rf

,0,1,2,3,4,5,6,7,8,9,10,11,12,prediction_label
0,1.4441,1.4422,1.4402,1.4428,1.4391,1.4386,1.4365,1.4327,1.4582,1.46,1.453,1.4475,1.4332,-2.601651

### HCN

In [23]:
datac1 = data[:,:14]
datac1[:,13:14] = data[:,15:16]
dfc1 = pd.DataFrame(datac1)
datac2 = data2[:,:14]
datac2[:,13:14] = data2[:,15:16]
testdatac = pd.DataFrame(datac2)

In [24]:
scn = setup(data = dfc1, train_size = 1.0 , test_data = testdatac, target='13', session_id = 123,
          normalize = True, normalize_method = 'minmax')

In [25]:
et = create_model('et', fold=5)

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

In [26]:
predictions_et = predict_model(et, data=new_data)
predictions_et

,0,1,2,3,4,5,6,7,8,9,10,11,12,prediction_label
0,1.4441,1.4422,1.4402,1.4428,1.4391,1.4386,1.4365,1.4327,1.4582,1.46,1.453,1.4475,1.4332,-6.33555

In [27]:
rf = create_model('rf', fold=5)

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

In [28]:
predictions_rf = predict_model(rf, data=new_data)
predictions_rf

,0,1,2,3,4,5,6,7,8,9,10,11,12,prediction_label
0,1.4441,1.4422,1.4402,1.4428,1.4391,1.4386,1.4365,1.4327,1.4582,1.46,1.453,1.4475,1.4332,-6.631918

### NH3

In [29]:
datac1 = data[:,:14]
datac1[:,13:14] = data[:,16:17]
dfc1 = pd.DataFrame(datac1)
datac2 = data2[:,:14]
datac2[:,13:14] = data2[:,16:17]
testdatac = pd.DataFrame(datac2)

In [30]:
snh = setup(data = dfc1, train_size = 1.0 , test_data = testdatac, target='13', session_id = 123, 
          normalize = True, normalize_method = 'minmax')

In [31]:
et = create_model('et', fold=5)

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

In [32]:
predictions_et = predict_model(et, data=new_data)
predictions_et

,0,1,2,3,4,5,6,7,8,9,10,11,12,prediction_label
0,1.4441,1.4422,1.4402,1.4428,1.4391,1.4386,1.4365,1.4327,1.4582,1.46,1.453,1.4475,1.4332,-8.204511

In [33]:
rf = create_model('rf', fold=5)

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

In [34]:
predictions_rf = predict_model(rf, data=new_data)
predictions_rf

,0,1,2,3,4,5,6,7,8,9,10,11,12,prediction_label
0,1.4441,1.4422,1.4402,1.4428,1.4391,1.4386,1.4365,1.4327,1.4582,1.46,1.453,1.4475,1.4332,-9.685787

### Opacity

In [35]:
datac1 = data[:,:14]
datac1[:,13:14] = data[:,17:18]
dfc1 = pd.DataFrame(datac1)
datac2 = data2[:,:14]
datac2[:,13:14] = data2[:,17:18]
testdatac = pd.DataFrame(datac2)

In [36]:
snh = setup(data = dfc1, train_size = 1.0 , test_data = testdatac, target='13', session_id = 123, 
          normalize = True, normalize_method = 'minmax')

In [37]:
et = create_model('et', fold=5)

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

In [38]:
predictions_et = predict_model(et, data=new_data)
predictions_et

,0,1,2,3,4,5,6,7,8,9,10,11,12,prediction_label
0,1.4441,1.4422,1.4402,1.4428,1.4391,1.4386,1.4365,1.4327,1.4582,1.46,1.453,1.4475,1.4332,-2.289427

In [39]:
rf = create_model('rf', fold=5)

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

In [40]:
predictions_rf = predict_model(rf, data=new_data)
predictions_rf

,0,1,2,3,4,5,6,7,8,9,10,11,12,prediction_label
0,1.4441,1.4422,1.4402,1.4428,1.4391,1.4386,1.4365,1.4327,1.4582,1.46,1.453,1.4475,1.4332,-2.391759